### ISSUE TITLE
Support copying unexported fields

### ISSUE THREAD

**Issue by Carrotman42** [jinzhu/copier#111]
## Describe the feature

I would like to have copier support copying to/from unexported fields. e.g., it would be nice if this correctly copied everything: https://play.golang.org/p/VJCuOmRasov

If there is some Go-level restriction to this, consider allowing users to define their own copy implementations for the type (e.g. look for a Copy() method on types which is invoked by the library), or something like that).

## Motivation

Sometimes for type design I do not want to export some field, but I still want to support deep-copying it.

**Comment by joshhardy** [comment]
@Carrotman42 I believe my PR #113 resolves this issue.

#113 has not been merged into the main project yet, but you can use it on my fork with a [replace](https://golang.org/ref/mod#go-mod-file-replace) in your `go.mod` like this
```go
replace github.com/jinzhu/copier => github.com/joshhardy/copier v0.3.3-0.20210917191521-72a9334486c4
```

**Comment by Carrotman42** [comment]
Looks like the PR was merged, thanks @jinzhu !
