### ISSUE TITLE
Copy map with slice-type value panic

### ISSUE THREAD

**Issue by studentliying** [jinzhu/copier#117]
## Reproducible Example
```
fromMap := make(map[string][]int32)
slice := []int32{1, 2}
fromMap["key1"] = slice
toMap := make(map[string][]int32)
copier.Copy(&toMap, fromMap)
```

## Description
copy a map which has slice-type value will report error: reflect.Value.Addr of unaddressable value

**Comment by cavanwang** [comment]
<img width="1040" alt="bug" src="https://user-images.githubusercontent.com/22739988/148535878-e35ea183-00b0-44ff-b32e-568c38b6d2be.png">

**Comment by cavanwang** [comment]
should fix in copier.go

**Comment by cavanwang** [comment]
I fixed the bug on  https://github.com/jinzhu/copier/pull/124, maybe it can be closed.
