### ISSUE TITLE
Struct with pointers

### ISSUE THREAD

**Issue by martijn-dd** [jinzhu/copier#12]
At the moment I am unable to copy struct A to struct B.
It does not copy because this check:  fromField.Type().AssignableTo(toField.Type()) on line 73 returns false. It is false because fromField type is *string and toField type is string.
Is it possible to copy these two kind of structs?

```
type A struct {
    Title *string
    Description *string
    Status *bool
}
```

```
type B struct {
    Title string
    Description string
    Status bool
}
```

**Comment by kchugalinskiy** [comment]
You may try using my fork, I've added support for this and opened a pull request

**Comment by martijn-dd** [comment]
Thanks. I'll give it a try.

**Comment by jinzhu** [comment]
merged that PR, thank you @kchugalinskiy
