### ISSUE TITLE
无法复制某些字段

### ISSUE THREAD

**Issue by ZhangHu1225** [jinzhu/copier#129]
## Your Question
源:
<img width="677" alt="image" src="https://user-images.githubusercontent.com/37826977/155936890-c2c5498a-fa81-4ab1-9033-fc2458cea8fc.png">

目标:
<img width="455" alt="image" src="https://user-images.githubusercontent.com/37826977/155936946-1bcb4ceb-b3e0-4532-8461-82fa3eec78fa.png">

结果:
<img width="560" alt="image" src="https://user-images.githubusercontent.com/37826977/155937020-506ef380-0cd9-4197-b6a6-81eba14ab18b.png">

**Id没有正确复制进去.
另外如何把time.Time 复制时转换为timestamppb.Timestamp**

**Comment by pupilji** [comment]
1. 没有复制成功的原因应该是：
`AlbumAlbumParam` 的 `ChildId` 和 `AlbumAlbums` 的 `ChildID` 字段名不同。
可以参考 [usage](https://github.com/jinzhu/copier#usage) 中的 `EmployeCode` 字段
2. 类型转换可以参考 [usage](https://github.com/jinzhu/copier#usage) `DoubleAge` 字段，在一个 func 中转换类型

**Comment by ZhangHu1225** [comment]
1:  结构体加了copier tag, 可以正常复制, 我有个小疑惑, 复制字段不是通过json这个tag 匹配的吗
2:如果是两个同名字段但类型不一致, 似乎不能使用 func DoubleAge 这种形式.

**Comment by pupilji** [comment]
@ZhangHu1225 
1. 我理解 `json` 这个 tag 是用来解析 json 的，现在你需要用 `copier.Copy()` ,所以肯定需要用 copier 规定的 tag
2. 可以看到 [usage](https://github.com/jinzhu/copier#usage) 中的 EmployeCode 字段，它和 `from` 和 `to` 中对应字段名是不同的，你也可以试下用一个与这个名字不同名的方法转换，用 `copier` 的 tag 让复制走这个方法

**Comment by zedisdog** [comment]
这里有个问题 A是grpc的结构体(自动生成的)  B是gorm的结构体(自动生成的) 当是这样一种情况的时候 而我又不想改生成的代码 就比较尴尬了
