### ISSUE TITLE
如果可以的话，能否加一个json与结构体的互相转换

### ISSUE THREAD

**Issue by Jaylenwa** [jinzhu/copier#172]

**Comment by daidai21** [comment]
"encoding/json" 都支持的么

**Comment by Jaylenwa** [comment]
> "encoding/json" 都支持的么

官方的这个好像不支持嵌套结构体转json或者嵌套json转结构体

**Comment by Jaylenwa** [comment]
> "encoding/json" 都支持的么

官方的这个好像无法支持嵌套json转嵌套结构体？ 我也不是很确定，而且转换步骤太多太繁琐

**Comment by Jaylenwa** [comment]
> "encoding/json" 都支持的么

抱歉，我的问题问错了，我想问的是，能否支持map[string]interface{} 嵌套转嵌套结构体

**Comment by Jaylenwa** [comment]
抱歉，我的问题问错了，我想问的是，能否支持map[string]interface{} 嵌套转嵌套结构体
