### ISSUE TITLE
Current status of this project

### ISSUE THREAD

**Issue by uded** [jinzhu/copier#173]
This project seems to be maintained on-and-off. Many PRs, many tickets, and not a lot of loving. Would it be wise to add more maintainers to it? @jinzhu, what is the current status of the game here...

**Comment by jinzhu** [comment]
Hi @uded 

The project is used a lot internally, but I don't have much time to check out those new issues/pull requests, and would be glad to add more maintainers if someone is interested. Do you want to be one of the maintainers?

**Comment by uded** [comment]
I would be happy to help out. I use this library extensively across many projects so for me it's one of the crucial ones.

**Comment by jinzhu** [comment]
Hi @uded

Just invited you as a collaborator, please checkout your email, maybe we are start from current existing pull requests, let me know if you have any questions.

Thank you.
