### ISSUE TITLE
Next version Release? 

### ISSUE THREAD

**Issue by patilakshay227** [jinzhu/copier#179]
Hi Team,

I wanted to know when the next version release is planned. 
Could you please release the next version as [very important fix](https://github.com/jinzhu/copier/pull/154/commits/ebbc03421eb99d6fee2b80b23976a0cd1828c772) (support for Interfaces in deep copy) is fixed 

If not, please confirm if the latest master is backward compatible.

@jinzhu

**Comment by PaluMacil** [comment]
@jinzhu I'm also hoping for a new release because of the case sensitive option

**Comment by jinzhu** [comment]
Just released v0.4.0
