### ISSUE TITLE
Copy unexpected behavior when two fields have same lower case name

### ISSUE THREAD

**Issue by matthieujoossen** [jinzhu/copier#192]
## Reproducible Example

https://go.dev/play/p/FGICZtx63e2

## Description

If I have a structure with two fields with same lower case name (ex `A` and `a`) then copy is not working as expected.

**Comment by matthieuzbo** [comment]
RTFM (shame on me): https://github.com/jinzhu/copier#copy-with-option

Use `copier.CopyWithOption` with `CaseSensitive` solve the issue (https://go.dev/play/p/dtcBJUQgsVP).

@jinzhu you can close this issue.
