### ISSUE TITLE
addition to docs

### ISSUE THREAD

**Issue by dgaedcke** [jinzhu/copier#21]
Can you please say if there are any problem when field name on on Struct is Capital, and other (same name) starts with (small) lowercase letter.

Also, what happens with embedded fields....do they get copied too??

**Comment by jinzhu** [comment]
For embedded fields, they will be copied.

> when field name on on Struct is Capital, and other (same name) starts with (small) lowercase letter

Which won't be copied, as go can't access lowercase fields out of your package.
