### ISSUE TITLE
Copy with nested pointer to struct causes panic

### ISSUE THREAD

**Issue by sudo-suhas** [jinzhu/copier#31]
The following code causes a panic:

```go
package main

import "github.com/jinzhu/copier"

func main() {
	type nested struct {
		A string
	}
	type parentA struct {
		*nested
	}
	type parentB struct {
		*nested
	}
	a := parentA{nested: &nested{A: "a"}}
	b := parentB{}

	copier.Copy(&b, &a)
}

```

stack trace:
```
$ go run copier_panic.go
panic: reflect: indirection through nil pointer to embedded struct

goroutine 1 [running]:
reflect.Value.FieldByIndex(0x4d4fe0, 0xc04206e020, 0x199, 0xc0420500d0, 0x2, 0x2, 0x0, 0x568f40, 0x4c8a00)
        C:/tools/go/src/reflect/value.go:804 +0x276
reflect.Value.FieldByName(0x4d4fe0, 0xc04206e020, 0x199, 0x4b5ea6, 0x1, 0x4c8a00, 0xc042044250, 0x198)
        C:/tools/go/src/reflect/value.go:820 +0x16e
github.com/jinzhu/copier.Copy(0x4c2a60, 0xc04206e020, 0x4c2a20, 0xc04206e018, 0x0, 0x0)
        E:/workspace/golang/src/github.com/jinzhu/copier/copier.go:71 +0x491
main.main()
        E:/workspace/golang/src/playground/copier_panic.go:18 +0xb1
exit status 2
```

The issue originates from this:
https://github.com/jinzhu/copier/blob/db4671f3a9b8df855e993f7c94ec5ef1ffb0a23b/copier.go#L71

Is this something that can be fixed in `copier`? I don't know enough about reflection but if you can guide me, I can make a PR to fix this.

**Comment by PumpkinSeed** [comment]
Possible it's trying to call the `reflectValue.Elem()` on a nil `reflect.Value`, so it won't have an exact `Elem()`. But correct me if I'm not right.

**Comment by bazaglia** [comment]
@sudo-suhas have you found any fix for this?

**Comment by sudo-suhas** [comment]
No.

**Comment by qzyse2017** [comment]
```go
b.nested = &nested{}
```
initialize the pointer can avoid panic.

**Comment by PumpkinSeed** [comment]
@qzyse2017 Can't agree, it's just a temporary solution. What if we have 300 nested field? It should be handled inside the library, if the nested field is nil, then reflect.New with the type of the field.

**Comment by georgysavva** [comment]
Hey. Any update on this? Is fix coming to the library?

**Comment by math-nao** [comment]
This example use unexported anonymous fields. Unexported fields cannot be copied to.
PR #72 adds support for exported anonymous fields and avoid panic in case of unexported anonymous fields.
