### ISSUE TITLE
Nested Slice getting copied by reference.

### ISSUE THREAD

**Issue by bhupkasUber** [jinzhu/copier#33]
Issue demonstrated in following code snippet.

```
package main

import (
	"fmt"
	"github.com/jinzhu/copier"
)

type A struct {
	X []int
}

type B struct {
	X []int
}

func main() {
	x := []int{1, 50}
	a := A{X: x}
	b := B{}
	copier.Copy(&b, a)
	fmt.Printf("X0 in B %v %v\n", b.X[0], b.X[1]) // Returns 1
	fmt.Printf("X0 in A %v %v\n", a.X[0], a.X[1]) // Returns 1
	a.X[0] = -1
	a.X[1] = -50
	fmt.Printf("X in B %v %v\n", b.X[0], b.X[1]) // Returns -1
	fmt.Printf("X in A %v %v\n", a.X[0], a.X[1]) // Returns -1
}

```

**Comment by sudersen** [comment]
I too faced the same issue. I had an internal pointer to a struct instead an array. 

For eg:

```
type A struct {
    B *struct {
        S string
    }
}
```

**Comment by con-ji** [comment]
Yep, I have the same issue with nested pointers - it appears that pointers to nested objects point to the same object, causing any changes to be reflected in the original and all copies.

**Comment by shahbazahmed1269** [comment]
Faced similar issue while trying to copy struct objects containing child struct which in turn had array field.

**Comment by SavostinVladimir** [comment]
I have the same issue with map. I need to copy only keys and values from one map to another, but get the same pointers for both...

**Comment by seaguest** [comment]
I have the same issue, I found [deepcopy](github.com/mohae/deepcopy) works fine, but it doesn't support copy(src, dst) method.

**Comment by Nerzal** [comment]
I can also confirm, this feature is broken, as it does not work with nested pointers

**Comment by math-nao** [comment]
most of use cases reported in comments should work with latest version and DeepCopy option (PR #62 , PR #70 have been merged in latest version)
