### ISSUE TITLE
panic when copying field with same name but different type

### ISSUE THREAD

**Issue by tori3ama** [jinzhu/copier#43]
It's a bit similar to #17:

```package main

import (
	"log"

	"github.com/jinzhu/copier"
)

type x struct{ Name string }

type structSameName1 struct {
	A string
	B []x
}

type structSameName2 struct {
	A string
	B x
}

func main() {
	obj1 := structSameName1{A: "123", B: []x{{Name: "ee"}}}
	obj2 := &structSameName2{}
	err := copier.Copy(obj2, &obj1)
	log.Println(err)
}
```

Running this will lead to panic:
```panic: reflect: call of reflect.Value.FieldByName on slice Value```

Not sure if this is a bug, but it won't panic in an old e15f8e2a. And thanks for your time on this project :)

**Comment by nevernet** [comment]
yep, it's an issue, could you push an pull request?
