### ISSUE TITLE
Thanks and these benchmark

### ISSUE THREAD

**Issue by frederikhors** [jinzhu/copier#66]
Have you seen these benchmarks here? https://github.com/gotidy/copy#benchmark

What do you think about it? Can we improve by taking a cue from there?

The difference is very high.

Thanks for your effort and your help. 😃

**Comment by jinzhu** [comment]
Hello @frederikhors 

The lib doesn't care about performance, the performance could improve a lots if cut down some features, but I think if the performance really matters and slow down your application, you should not use any this kinds of libs, but assign the value by yourself.
