### ISSUE TITLE
 v.IsZero undefined 

### ISSUE THREAD

**Issue by anita810** [jinzhu/copier#68]
I am using your library in my project.
Compilation Errror:- 
`vendor/github.com/jinzhu/copier/copier.go:211:10: v.IsZero undefined (type reflect.Value has no field or method IsZero)`

**Comment by BastLeblanc** [comment]
+1 seems related to an addition in a recent commit " Use IsZero to check value is empty or not " https://github.com/jinzhu/copier/commit/777a6896cc7c6f8732f58ecfb102bdd9da2a214a

@jinzhu can you check out this one as it breaks every project using this library?

**Comment by jinzhu** [comment]
Golang 1.13+ required
