### ISSUE TITLE
[Bug] crashed with nested struct

### ISSUE THREAD

**Issue by tubzby** [jinzhu/copier#76]
## Reproducible Example

https://play.golang.org/p/INvrWLUd6BD

## code samples

```golang
package main

import (
	"github.com/jinzhu/copier"
)

func main() {
	type Basic struct {
		ID   int
		Name string
		Addr string
	}

	type S struct {
		Basic
		Level int
	}

	s1 := S{}

	var s2 S
	copier.Copy(&s2, s1)

}

```

## Description
Crashed with nested struct. seemed cause by copier.go+193.

```golang
if f, ok := dest.Type().FieldByName(name); ok {
for idx, x := range f.Index {
	destFieldKind := dest.Field(x).Kind()
```

as mentioned by: https://golang.org/pkg/reflect/#StructField

"    Index     []int     // index sequence for Type.FieldByIndex ", the index can't used by dest.Field(x)

**Comment by zhengwh** [comment]
yes,I have the same problem。 when the length of the sub struct's field is more than parent's, we will find this crash.

`package main

import (
	"github.com/jinzhu/copier"
	"log"
)


type L2BaseValue struct {
	BaseValue
	L2A int
}

type BaseValue struct {
	A int
	B int
	C int
}

type ToValue struct {
	L2BaseValue
}

func BaseDemo(){
	head := ToValue{}

	base :=L2BaseValue{}
	base.B=21

	err := copier.Copy(&head.L2BaseValue, &base)
	if err != nil {
		log.Println(err)
		return
	}
}


func main(){
	BaseDemo()
	log.Println("end")
}
`

**Comment by gabyx** [comment]
Same problem.

**Comment by gabyx** [comment]
Is there any resolution?

**Comment by phuoc-insignia** [comment]
this PR https://github.com/jinzhu/copier/pull/82 fix this problem
