### ISSUE TITLE
[Bug] Panic on SetMapIndex when using map[x]interface{}

### ISSUE THREAD

**Issue by maeglindeveloper** [jinzhu/copier#79]
## Reproducible Example
https://play.golang.org/p/RJOgBhY1oGo

## Description

Hi everyone, 

I'm facing again a panic using the CopyWithOptions() method.
See above the example.

It seems this is related to `map[x]interface{}`
@jinzhu

**Comment by grount** [comment]
Having the same issue on `map[string]interface{}`.
`panic: reflect: call of reflect.Value.SetMapIndex on interface Value`

**Comment by maeglindeveloper** [comment]
@jinzhu any advice on this ? :)

**Comment by rahulkhairwar** [comment]
@jinzhu the below line doesn't actually set `to`'s value to a map :
```to.Set(reflect.MakeMapWithSize(toType, from.Len()))```
Later, ```to.SetMapIndex(toKey, toValue)``` causes panic, as `to` is not of type map.
Any way to resolve this?

**Comment by jinzhu** [comment]
This should been fixed in latest version
