### ISSUE TITLE
[Bug] Ordering of field in Struct leads to panic

### ISSUE THREAD

**Issue by phuoc-insignia** [jinzhu/copier#84]
## Reproducible Example

https://play.golang.org/p/hZnz2rIy2_Z

## Description
Please look at the example code.
I can copy this struct: 
```
type Work struct {
	ID      string  `json:"id"`
	Name    string  `json:"name"`
	UserID  *string `json:"user_id"`
	Website *string `json:"website"`
	Timestamps
}
```

but not this:
```
type NotWork struct {
	ID      string  `json:"id"`
	UserID  *string `json:"user_id"`
	Name    string  `json:"name"`
	Website *string `json:"website"`
	Timestamps
}
```

**Comment by zerosnake0** [comment]
@phuoc-insignia plz check with the latest (v0.2.5)

**Comment by phuoc-insignia** [comment]
> @phuoc-insignia plz check with the latest (v0.2.5)

Thanks for quick reponse. It works perfertly now!
