### ISSUE TITLE
能提供一个自定义字段映射的功能么

### ISSUE THREAD

**Issue by oneone1995** [jinzhu/copier#87]
## Describe the feature
有两个struct的属性字段名不同，但是含义却是相同的，例如：

```go
type User struct {
    Name string
}

type UserVo struct{
    UserName string
}
```

Java中类似的库[orika](https://github.com/orika-mapper/orika)就提供了下面的处理方案。

```java
    mapperFactory.classMap(PersonSource.class, PersonDestination.class)
       .field("firstName", "givenName")
       .field("lastName", "sirName")
       .byDefault()
       .register();
```

## Motivation
这种场景还是比较常见的，希望能提供类似的功能支持

## Related Issues
刚发现PR中前两天正好有人提了。
[ Copy different field name from tag flag #86 ](https://github.com/jinzhu/copier/pull/86)

**Comment by jinzhu** [comment]
done.
