### ISSUE TITLE
[Bug] Deep copy of struct with interface panics

### ISSUE THREAD

**Issue by Jake-Convictional** [jinzhu/copier#91]
## Reproducible Example

https://play.golang.org/p/MxExk1tAYqu

## Description

Performing a deep copy of a struct that has an unset `interface{}` field will cause a panic with: `panic: reflect: New(nil)`. It looks like copier is assuming the field will have an underlying type, which isn't always the case.

**Comment by jonahgeorge** [comment]
I've also experienced this recently

**Comment by janik-cloudflare** [comment]
I think this can be closed; @Jake-Convictional's example no longer panics after commit 1cde854d294d50c84ed083b75c955fbe7d3713cc.

Thank you so much @jinzhu for fixing this!
