### ISSUE TITLE
您好,为什么嵌套的结构体,无法复制呢

### ISSUE THREAD

**Issue by shenqidebaozi** [jinzhu/copier#94]
![image](https://user-images.githubusercontent.com/35397691/111631984-fe39b500-882e-11eb-912a-21a8398a8243.png)
copy destination is invalid

**Comment by junneyang** [comment]
解决了吗~

**Comment by mingzaily** [comment]
同问 嵌套结构体要咋搞。。

**Comment by yuezhongtao** [comment]
当前版本未解决的问题为啥close issue？
